# Generated by Django 5.2.7 on 2025-10-26 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTermTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, verbose_name='Derslik Adi')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ders Kodu')),
                ('title', models.CharField(max_length=200, verbose_name='Ders Basligi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ders Aciklamasi')),
                ('course_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBinderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Soru Başlığı')),
                ('content', models.TextField(verbose_name='Soru İçeriği')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_priority', models.IntegerField(editable=False, max_length=10, verbose_name='Onem Sirasi')),
                ('class_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classtermtest', verbose_name='Bolum ve Donem')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coursetest', verbose_name='Ana Ders')),
                ('question_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sorunun_Sahibi', to=settings.AUTH_USER_MODEL, verbose_name='Sorunun Sahibi')),
                ('question_current_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sorunun Su Anki Sorumlusu')),
                ('question_old_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sorunun_Eski_Sorumlusu', to=settings.AUTH_USER_MODEL, verbose_name='Sorunun Eski Sorumlusu')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Cevap Icerigi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.questionbindertest', verbose_name='Soru')),
            ],
        ),
    ]
